- name: create directory for certs
  ansible.builtin.file:
    path: "{{ playbook_dir }}/certs"
    state: directory
    mode: '0755'

- name: Generate Root CA private key
  community.crypto.openssl_privatekey:
    path: "{{ playbook_dir }}/certs/ca.key"
    size: 4096
    type: RSA

- name: Generate Root CA certificate
  community.crypto.x509_certificate:
    path: "{{ playbook_dir }}/certs/ca.crt"
    privatekey_path: "{{ playbook_dir }}/certs/ca.key"
    provider: selfsigned

- name: Generate Private Key for Vault
  community.crypto.openssl_privatekey:
    path: "{{ playbook_dir }}/certs/vault.{{ domain_name }}.key"
    size: 4096
    type: RSA

- name: Generate Root CA CSR
  community.crypto.openssl_csr:
    path: "{{ playbook_dir }}/certs/vault.{{ domain_name }}.csr"
    privatekey_path: "{{ playbook_dir }}/certs/vault.{{ domain_name }}.key"
    common_name: "vault.{{ domain_name }}"
    organization_name: "Interway"
    country_name: "SK"
    state_or_province_name: "Slovak Republic"
    locality_name: "Bratislava"
    subject_alt_name:
      - "DNS:vault.{{ domain_name }}"
      - "DNS:vault-1.{{ domain_name }}"
      - "DNS:vault-2.{{ domain_name }}"
      - "DNS:vault-3.{{ domain_name }}"
    basic_constraints:
      - CA:TRUE
    basic_constraints_critical: yes
    key_usage:
      - keyCertSign
      - digitalSignature
      - cRLSign
    key_usage_critical: yes

- name: Generate Vault Certificate signed by CA
  community.crypto.x509_certificate:
    path: "{{ playbook_dir }}/certs/vault.{{ domain_name }}.crt"
    csr_path: "{{ playbook_dir }}/certs/vault.{{ domain_name }}.csr"
    privatekey_path: "{{ playbook_dir }}/certs/vault.{{ domain_name }}.key"
    provider: ownca
    ownca_path: "{{ playbook_dir }}/certs/ca.crt"
    ownca_privatekey_path: "{{ playbook_dir }}/certs/ca.key"
    ownca_not_after: +365d
