---
- name: Validate configuration variables
  ansible.builtin.include_tasks: validate.yml
  tags: always

- name: Install HashiCorp Vault
  ansible.builtin.include_tasks: install.yml
  when: not vault_config_only | bool
  tags: install

- name: Configure HashiCorp Vault
  ansible.builtin.include_tasks: config.yml
  tags: config

- name: Manage TLS certificates
  ansible.builtin.include_tasks: tls.yml
  tags: tls

- name: Manage vault service
  ansible.builtin.include_tasks: service.yml
  when: not vault_config_only | bool
  tags: service

- name: Initialize and unseal Vault
  ansible.builtin.include_tasks: init_unseal.yml
  when: not vault_config_only | bool
  tags: init_unseal

- name: Enable audit device
  ansible.builtin.include_tasks: audit.yml
  when:
    - not vault_config_only | bool
    - vault_audit_enabled | bool
  tags: audit
