---
# ==============================================================================
# Manage the vault systemd service.
# This file is only included when vault_config_only=false.
# ==============================================================================

- name: Enable and start Vault service
  ansible.builtin.systemd:
    name: vault
    state: "{{ vault_service_state }}"
    enabled: "{{ vault_service_enabled | bool }}"
    daemon_reload: true
  tags: service
